- name: set prompt
  ansible.builtin.shell: set-prompt grafana

- name: copy repo file
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: Install grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: start grafana server
  ansible.builtin.systemd_service:
    name: grafana-server
    state: started
    enabled: yes

- name: Copy test.json file
  ansible.builtin.copy:
    src: test.json
    dest: /tmp/test.json

- name: Create dashboard
  community.grafana.grafana_dashboard:
    url: http://localhost:3000
    url_username: admin
    url_password: admin123
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: /tmp/test.json


