- name: Set Prompt
  ansible.builtin.shell: set-prompt prometheus

- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus

- name: Download Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true
    owner: prometheus
    group: prometheus

- name: Update Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-2.52.0.linux-amd64/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Update Alerts
  ansible.builtin.template:
    src: alert_rules.yml
    dest: /opt/prometheus-2.52.0.linux-amd64/alert_rules.yml
    owner: prometheus
    group: prometheus

- name: Copy Prometheus systemd file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus Service
  ansible.builtin.include_role:
    name: common
    tasks_from: start-service
  vars:
    service_name: prometheus


- name: Download AlertManager
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true
    owner: prometheus
    group: prometheus

- name: Update AlertManager configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager-0.27.0.linux-amd64/alertmanager.yml
    owner: prometheus
    group: prometheus

- name: Copy AlertManager systemd file
  ansible.builtin.template:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: Start Alertmanager Service
  ansible.builtin.include_role:
    name: common
    tasks_from: start-service
  vars:
    service_name: alertmanager
